---
- name: Install haproxy
  apt:
    name:
      - haproxy

- name: Change haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    mode: 0644
  notify:
    - Restart haproxy.service
