---

- name: apt update
  apt:
    update_cache: yes

- name: Install python modules
  apt:
    name:
      - python3-pip
      - python3-dev
      - libpq-dev

- name: Stop postgresql.service
  systemd:
    name: postgresql.service
    state: stopped
    enabled: no

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: Install patroni
  pip:
    name:
      - psycopg2
      - patroni[etcd]

- name: Create patroni.service
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    mode: 0644

- name: Create /data/patroni
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  loop:
    - /data/patroni
    - /data/patroni/data
    - /etc/patroni

- name: Create patroni.yml
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    owner: root
    mode: 0644

- name: Delete old postgres data
  file:
    path: "/var/lib/postgresql/{{ postgresql_version }}/main"
    state: absent
  when: not patroni_master

- name: Enabled patroni.service
  service:
    name: patroni.service
    enabled: yes

- name: Start patroni.service master
  systemd:
    name: patroni.service
    state: restarted
  when: patroni_master

- name: Start patroni.service slaves
  service:
    name: patroni.service
    state: restarted
    sleep: 30
  when: not patroni_master
