---
- hosts: app1
  become: yes

  tasks:
    - name: Disabled firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
        masked: yes

    - name: Disable SELinux
      selinux:
        state: disabled
      when: ansible_selinux.status == "enabled"

    - name: Setenforce 0
      command:
        setenforce 0
      when: ansible_selinux.status == "enabled"
