---
nginx_sites:
  backend:
    - listen 80
    - server_name {{ app_ip }}
    - location / { root {{ frontend_app_dist }}/current/build; }
    - location /api { proxy_pass http://{{ app_ip }}:5000/api/advertisement; }
